sudo: false

services: redis-server

language: node_js

cache: node_modules

node_js:
- "stable"

install:
- npm install

after_success:
- npm run coveralls

deploy:
  provider: npm
  email: d.dodzin@gmail.com
  api_key:
    secure: I9V8McFy9RRY5raRlOJK7lJrHazVTNZ8sOXSs/GF6n0nebo7cVvtn3NIj/SbsAJFwPqC5UQgQFkraJZxNYDQLcVxd6lpm5LcnYtw7cqkHaQQKYyKb7UEgpx3KmCQCsX2AIsKLYC17zBZYDn6qMWvx2y1Iddava3vg/hEIfCt3A2D7bL0puzCjBaebL8SfhuN65/BEzBUt5YzKfykyrCDDYmzGKKjLKSaA5PsXnqppZcLBEoYkrMrKq5ocKQKbNCkpKhG6Qw8hHdsG1VOURxTZQPIaPlQ98mB/PvXjDPU4dyRZDy9/VZarlUQY8u7EhzDVWy2anDV7kHbUMiSTzv/40US4QYf6QWdVFlvkfXbgAAY9xWxE4jWrmJSY83PTE2boGD3QhSZpCs4OcoYgZdIHzhHLydLidQjMRbi5tO8UXsnj7f6A80YbE/8HHJF7jIXwOJpbpWjWFIbYuvUbhZOi5F1saz1J4lHeQ3UgVPXRSbkUMa0sn322T5Tlgi+SEL0NkW9ae/ENJznMmFXiBDcjVvZjk9ET8GE2OwQ8wBJOZTlmf4TfHXvzAfMGmTumoAUipZUUpsAy0io89EXEgO446ykXfM9vxykwcR6CxJfyLfjOa6nDP+nNpt7PEho+GFNz17856YM83jggpnJlGnh1c30QjTJKVJznnIIHekS+kw=
  on:
    branch: master
